name: Deploy to Hostinger

on:
  push:
    branches:
      - master # Ou main, se for o caso

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Obter código do repositório
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Instalar dependências
        run: npm ci

      - name: 🏗️ Fazer o Build do projeto (Vite)
        run: npm run build

      - name: 🚀 Deploy para a Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/   # Envia apenas a pasta gerada pelo build
          server-dir: ./ # Ajustado para a raiz da conta FTP
          protocol: ftp
          dangerous-clean-slate: false
          timeout: 600000
