name: Deploy to Hostinger

on:
  push:
    branches:
      - master # Ou main, se for o caso

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Obter código do repositório
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: 📦 Instalar dependências
        run: npm ci

      - name: 🏗️ Fazer o Build do projeto (Vite)
        run: npm run build

      - name: 🚀 Deploy para a Hostinger via lftp
        run: |
          sudo apt-get install -y lftp
          lftp -c "set ftp:ssl-allow yes;
          set ftp:ssl-force true;
          set ftp:ssl-protect-data true;
          set ftp:ssl-protect-list true;
          set ssl:verify-certificate no;
          open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }};
          mirror -R ./dist/ ./;
          quit"
